# Generated by Django 5.2.8 on 2025-11-21 11:07

import django.db.models.deletion
import videos.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do Evento')),
                ('frame_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL da Moldura')),
                ('music_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL da Música')),
                ('music_start_time_sec', models.IntegerField(default=0, verbose_name='Início da Música (s)')),
                ('music_end_time_sec', models.IntegerField(default=0, verbose_name='Fim da Música (s)')),
                ('effect_id', models.CharField(max_length=50, verbose_name='ID do Efeito')),
                ('event_date', models.CharField(max_length=20, verbose_name='Data do Evento')),
                ('is_finished', models.BooleanField(default=False, verbose_name='Finalizado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=100, unique=True)),
                ('video_file', models.FileField(upload_to=videos.models.video_upload_path)),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('PROCESSING', 'Processando'), ('COMPLETED', 'Concluído'), ('FAILED', 'Falhou')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='videos.event')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
