# Generated by Django 5.2.8 on 2025-11-23 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='frame_url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Caminho/URL da Moldura'),
        ),
        migrations.AlterField(
            model_name='event',
            name='music_url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Caminho/URL da Música'),
        ),
    ]
