# Generated by Django 5.2.8 on 2025-12-02 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_code', models.IntegerField(help_text='Código da versão (inteiro) para comparação', unique=True)),
                ('version_name', models.CharField(help_text='Nome da versão (ex: 1.0.0)', max_length=50)),
                ('apk_file', models.FileField(help_text='Arquivo APK para download', upload_to='apks/')),
                ('is_mandatory', models.BooleanField(default=False, help_text='Se a atualização é obrigatória')),
                ('release_notes', models.TextField(blank=True, help_text='Notas da versão')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Versão do App',
                'verbose_name_plural': 'Versões do App',
                'ordering': ['-version_code'],
            },
        ),
    ]
